Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -68,12 +68,14 @@ jobs:
           curl -LO https://github.com/telmich/gpm/archive/refs/tags/${{ env.GPM_VERSION }}.tar.gz
           curl -LO https://curl.se/download/curl-7.86.0.tar.gz
           curl -LO https://www.openssl.org/source/openssl-1.1.1k.tar.gz
+          curl -LO https://invisible-mirror.net/archives/ncurses/ncurses-6.2.tar.gz
           tar -xf v${{ env.MBEDTLS_VERSION }}.tar.gz
           tar -xjf libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
           tar -xf readline-${{ env.READLINE_VERSION }}.tar.gz
           tar -xf ${{ env.GPM_VERSION }}.tar.gz
           tar -xzf curl-7.86.0.tar.gz
           tar -xzf openssl-1.1.1k.tar.gz
+          tar -xzf ncurses-6.2.tar.gz
           git clone --depth=1 https://github.com/libimobiledevice/libplist
           git clone --depth=1 https://github.com/libimobiledevice/libimobiledevice-glue
           git clone --depth=1 https://github.com/libimobiledevice/libirecovery
@@ -99,6 +101,22 @@ jobs:
           set(CMAKE_C_FLAGS "${CFLAGS}")
           set(CMAKE_CXX_FLAGS "${CXXFLAGS}")
           EOF
+
+      - name: Build ncurses
+        run: |
+          cd ncurses-6.2
+          ./configure ${{ env.CONFIGURE_ARGS }} --without-debug --without-ada --without-manpages --without-progs --without-tests --with-terminfo-dirs=/etc/terminfo:/lib/terminfo:/usr/share/terminfo
+          make -j$(nproc)
+          make install DESTDIR=${{ env.DESTDIR }}
+          cd ..
+
+      - name: Verify ncurses installation
+        run: |
+          ls -l ${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libncurses.*
+          if [ ! -f "${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libncurses.a" ]; then
+            echo "libncurses.a not found!"
+            exit 1
+          fi
 
       - name: Build Mbed TLS
         run: |
@@ -140,7 +158,9 @@ jobs:
       - name: Build readline
         run: |
           cd readline-${{ env.READLINE_VERSION }}
-          ./configure ${{ env.CONFIGURE_ARGS }}
+          export CFLAGS="$CFLAGS -I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
+          export LDFLAGS="$LDFLAGS -L${{ env.DESTDIR }}${{ env.PREFIX }}/lib"
+          ./configure ${{ env.CONFIGURE_ARGS }} --with-curses
           make -j$(nproc)
           make install DESTDIR=${{ env.DESTDIR }}
           cd ..
@@ -351,7 +371,7 @@ jobs:
             ls -la
           fi
           cd ..
-          
+
       - name: Check configure output
         run: |
           cd libimobiledevice
@@ -368,16 +388,10 @@ jobs:
         run: |
           cd libirecovery
           export PKG_CONFIG_PATH=${{ env.DESTDIR }}${{ env.PREFIX }}/lib/pkgconfig:$PKG_CONFIG_PATH
-          export CFLAGS="$CFLAGS -I${{ env.DESTDIR }}${{ env.PREFIX }}/include/libusb-1.0 -I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
+          export CFLAGS="$CFLAGS -I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
           export LDFLAGS="$LDFLAGS -L${{ env.DESTDIR }}${{ env.PREFIX }}/lib"
-          export LIBPLIST_LIBS="-L${{ env.DESTDIR }}${{ env.PREFIX }}/lib -lplist-2.0"
-          export LIBPLIST_CFLAGS="-I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
-          export LIBIMOBILEDEVICE_GLUE_LIBS="-L${{ env.DESTDIR }}${{ env.PREFIX }}/lib -limobiledevice-glue-1.0"
-          export LIBIMOBILEDEVICE_GLUE_CFLAGS="-I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
-          export LIBUSB_LIBS="-L${{ env.DESTDIR }}${{ env.PREFIX }}/lib -lusb-1.0"
-          export LIBUSB_CFLAGS="-I${{ env.DESTDIR }}${{ env.PREFIX }}/include/libusb-1.0"
           ./autogen.sh
-          ./configure ${{ env.CONFIGURE_ARGS }} --enable-static --disable-shared
+          ./configure ${{ env.CONFIGURE_ARGS }} --enable-static --disable-shared LIBS="-lncurses"
           make -j$(nproc)
           make install DESTDIR=${{ env.DESTDIR }}
           cd ..
