Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,11 +67,13 @@ jobs:
           curl -LO https://mirror-hk.koddos.net/gnu/readline/readline-${{ env.READLINE_VERSION }}.tar.gz
           curl -LO https://github.com/telmich/gpm/archive/refs/tags/${{ env.GPM_VERSION }}.tar.gz
           curl -LO https://curl.se/download/curl-7.86.0.tar.gz
+          curl -LO https://www.openssl.org/source/openssl-1.1.1k.tar.gz
           tar -xf v${{ env.MBEDTLS_VERSION }}.tar.gz
           tar -xjf libusb-${{ env.LIBUSB_VERSION }}.tar.bz2
           tar -xf readline-${{ env.READLINE_VERSION }}.tar.gz
           tar -xf ${{ env.GPM_VERSION }}.tar.gz
           tar -xzf curl-7.86.0.tar.gz
+          tar -xzf openssl-1.1.1k.tar.gz
           git clone --depth=1 https://github.com/libimobiledevice/libplist
           git clone --depth=1 https://github.com/libimobiledevice/libimobiledevice-glue
           git clone --depth=1 https://github.com/libimobiledevice/libirecovery
@@ -246,18 +248,33 @@ jobs:
           fi
           echo "libtatsu installation verified successfully."
 
+      - name: Build OpenSSL
+        run: |
+          cd openssl-1.1.1k
+          ./Configure ${{ env.CONFIGURE_ARGS }} no-shared linux-x86
+          make -j$(nproc)
+          make install_sw DESTDIR=${{ env.DESTDIR }}
+          cd ..
+
+      - name: Verify OpenSSL installation
+        run: |
+          ls -l ${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libssl.a
+          ls -l ${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libcrypto.a
+          if [ ! -f "${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libssl.a" ] || [ ! -f "${{ env.DESTDIR }}${{ env.PREFIX }}/lib/libcrypto.a" ]; then
+            echo "OpenSSL libraries not found!"
+            exit 1
+          fi
 
       - name: Build libimobiledevice
         run: |
           cd libimobiledevice
           export PKG_CONFIG_PATH=${{ env.DESTDIR }}${{ env.PREFIX }}/lib/pkgconfig:$PKG_CONFIG_PATH
+          export OPENSSL_CFLAGS="-I${{ env.DESTDIR }}${{ env.PREFIX }}/include"
+          export OPENSSL_LIBS="-L${{ env.DESTDIR }}${{ env.PREFIX }}/lib -lssl -lcrypto"
           ./autogen.sh
-          ./configure ${{ env.CONFIGURE_ARGS }} --with-mbedtls --enable-static --disable-shared
+          ./configure ${{ env.CONFIGURE_ARGS }} --without-cython --enable-static --disable-shared
           make -j$(nproc)
           make install DESTDIR=${{ env.DESTDIR }}
-          mkdir -p ${{ env.DESTDIR }}/usr/local/lib
-          # Copy the .la file from the correct location
-          cp src/.libs/libimobiledevice-1.0.la ${{ env.DESTDIR }}/usr/local/lib/
           cd ..
 
       - name: Verify libimobiledevice .la file
